version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rpwhale-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xcpz750eeot"
s3_prefix = "rpwhale-bot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
